---
- name: Setup DNS (Unbound) and NTP server
  hosts: all
  become: true
  strategy: free
  gather_facts: true
  become_method: sudo
  tasks:

    - name: Install required system packages
      apt:
        pkg:
          - unbound
        state: latest
        update_cache: true

    - name: Disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Copy unbound config
      copy:
        src: ../files/dns/unbound.conf
        dest: /etc/unbound/unbound.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart unbound
    
  handlers:
    - name: Restart unbound
      ansible.builtin.systemd:
        name: unbound
        state: restarted
