---
- name: Setup ntp 
  hosts: all
  become: true
  strategy: free
  gather_facts: true
  become_method: sudo
  vars:
    - ipa_fqdn: ipa.kp.org
    - admin_password: admin12345
    - ds_password: admin12345
  tasks:
    - name: Install cockpit
      ansible.builtin.command: dnf -y install cockpit
      when: ansible_distribution == "Fedora"

    - name: Enable cockpit
      ansible.builtin.command: systemctl enable --now cockpit.socket

    - name: Add firewall rule for freeipa 
      ansible.builtin.command: firewall-cmd --add-service=freeipa-ldap --add-service=freeipa-ldaps --permanent

    - name: Install freeipa
      ansible.builtin.command: dnf -y install freeipa-server freeipa-server-dns bind-dyndb-ldap

    - name: "Set hostname to {{ ipa_fqdn }}" 
      ansible.builtin.command: "hostnamectl set-hostname {{ ipa_fqdn }}"

    - name: Add hostname to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ipa_fqdn }} ipa"


    - name: Disable ipv6 for now
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv6.conf.all.disable_ipv6 = 1"
        state: present
      when: ansible_distribution == "Fedora"

    - name: Disable ipv6 for now
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv6.conf.default.disable_ipv6 = 1"
        state: present
      when: ansible_distribution == "Fedora"

    - name: Disable ipv6 for now
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv6.conf.lo.disable_ipv6 = 1"
        state: present
      when: ansible_distribution == "Fedora"

    - name: Apply freshly added ipv6 kernel parameters
      ansible.builtin.command: sysctl -p

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Setup freeipa
      ansible.builtin.command: "ipa-server-install \
                                --unattended \
                                --setup-dns \
                                --hostname={{ ipa_fqdn }} \
                                --realm=KP.ORG \
                                --domain=KP.ORG \
                                --ds-password={{ ds_password }} \
                                --admin-password={{ admin_password }} \
                                --auto-forwarders \
                                --auto-reverse"


          #- name: Create a /docker/keycloak directory
          #  ansible.builtin.file:
          #    path: /docker/keycloak
          #    state: directory
          #    mode: 0755

          #- name: Copy docker-compose.yml to /docker/keycloak
          #  ansible.builtin.copy:
          #    src: docker-compose.yml
          #    dest: /docker/keycloak/docker-compose.yml
          #    mode: 0644

          #- name: Copy .env to /docker/keycloak
          #  ansible.builtin.copy:
          #    src: .env
          #    dest: /docker/keycloak/.env
          #    mode: 0644

          #- name: Start Keycloak
          #  ansible.builtin.command: docker compose up -d
          #  args:
          #    chdir: /docker/keycloak

          #- name: Create initial admin user
          #  ansible.builtin.command: docker exec -it keycloak /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master --user {{ keycloak_admin_user }} --password {{ keycloak_admin_password }}
          #  args:
          #    chdir: /docker/keycloak

          #- name: Restart Keycloak
          #  ansible.builtin.command: docker restart keycloak
          #  args:
          #    chdir: /docker/keycloak

          #- name: Create LDAP on keycloak

