---
- name: Setup freeipa server (LDAP) - Fedora
  hosts: all
  become: true
  strategy: free
  gather_facts: true
  become_method: sudo
  vars:
    - ipa_fqdn: ipa.kp.org
    - admin_password: admin12345
    - ds_password: admin12345
    - custom_ntp_server: 2.si.pool.ntp.org
  tasks:
    - name: Install cockpit
      ansible.builtin.command: dnf -y install cockpit
      when: ansible_distribution == "Fedora"

    - name: Enable cockpit
      ansible.builtin.command: systemctl enable --now cockpit.socket
      when: ansible_distribution == "Fedora"

    - name: Add firewall rule for freeipa 
      ansible.builtin.command: firewall-cmd --add-service=freeipa-ldap --add-service=freeipa-ldaps --permanent
      when: ansible_distribution == "Fedora"

    - name: Add fqdn to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ipa_fqdn }} ipa"
      when: ansible_distribution == "Fedora"

    - name: Reload the firewall
      ansible.builtin.command: firewall-cmd --reload
      when: ansible_distribution == "Fedora"

    - name: "Set hostname to {{ ipa_fqdn }}" 
      ansible.builtin.command: "hostnamectl set-hostname {{ ipa_fqdn }}"
      when: ansible_distribution == "Fedora"

    - name: Add hostname to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ipa_fqdn }} ipa"
      when: ansible_distribution == "Fedora"

    - name: Enable DL1 module stream 1/2
      ansible.builtin.command: dnf module enable -y idm:DL1
      when: ansible_distribution == "CentOS"

    - name: Enable DL1 module stream 2/2
      ansible.builtin.command: dnf distro-sync
      when: ansible_distribution == "CentOS"

    - name: Install freeipa
      ansible.builtin.command: dnf -y install freeipa-server freeipa-server-dns bind-dyndb-ldap
      when: ansible_distribution == "Fedora"

        #- name: enable IPv6 on the loopback interface
        #  ansible.builtin.lineinfile:
        #    path: /etc/sysctl.conf
        #    line: "net.ipv6.conf.all.disable_ipv6 = 0"
        #    state: present
        #  when: ansible_distribution == "Fedora"

        #- name: Apply freshly added ipv6 kernel parameters
        #  ansible.builtin.command: sysctl -p
        #  when: ansible_distribution == "Fedora"

        #- name: Reboot the server
        #  ansible.builtin.reboot:
        #    reboot_timeout: 600
        #  when: ansible_distribution == "Fedora"

    - name: Setup freeipa
      ansible.builtin.command: 
        cmd: "ipa-server-install \
              --unattended \
              --hostname={{ ipa_fqdn }} \
              --realm=KP.ORG \
              --domain=KP.ORG \
              --ds-password={{ ds_password }} \
              --admin-password={{ admin_password }} \
              --ntp-server={{ custom_ntp_server }}"
      when: ansible_distribution == "Fedora"

          #- name: Create a /docker/keycloak directory
          #  ansible.builtin.file:
          #    path: /docker/keycloak
          #    state: directory
          #    mode: 0755

          #- name: Copy docker-compose.yml to /docker/keycloak
          #  ansible.builtin.copy:
          #    src: docker-compose.yml
          #    dest: /docker/keycloak/docker-compose.yml
          #    mode: 0644

          #- name: Copy .env to /docker/keycloak
          #  ansible.builtin.copy:
          #    src: .env
          #    dest: /docker/keycloak/.env
          #    mode: 0644

          #- name: Start Keycloak
          #  ansible.builtin.command: docker compose up -d
          #  args:
          #    chdir: /docker/keycloak

          #- name: Create initial admin user
          #  ansible.builtin.command: docker exec -it keycloak /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master --user {{ keycloak_admin_user }} --password {{ keycloak_admin_password }}
          #  args:
          #    chdir: /docker/keycloak

          #- name: Restart Keycloak
          #  ansible.builtin.command: docker restart keycloak
          #  args:
          #    chdir: /docker/keycloak

          #- name: Create LDAP on keycloak

