---
- name: Setup ldap users - Fedora
  hosts: all
  become: true
  strategy: free
  gather_facts: true
  become_method: sudo
  vars:
    - users: [
        { "name": "Tilen", "surname" : "Ozbot", "username": "tilen",  "password": "tilen12345" },
        { "name": "Gasper", "surname" : "Spagnolo", "username": "gasper",  "password": "gasper12345" },
        { "name": "Matjaz", "surname" : "Pancur", "username": "matjaz",  "password": "matjaz12345" },
        { "name": "Mojca", "surname" : "Ciglaric", "username": "mojca",  "password": "mojca12345" },
    ]
  tasks:

    - name: Check if users already exist
      ansible.builtin.command: "ipa user-find {{ user.username }}"
      loop: "{{ users }}"
      loop_control:
        loop_var: user 
      register: user_exists
      ignore_errors: true 
      when: ansible_distribution == "Fedora"

    - name: Print user_exists
      ansible.builtin.debug:
        msg: "{{ user_exists.results[0].rc }}"
      when: ansible_distribution == "Fedora"

    - name: Setup users on freeipa
      ansible.builtin.command:
        cmd:  "ipa user-add --first={{ user.name }} --last={{ user.surname }}  {{ user.username }} --password"
      args:
        stdin: "{{ user.password }}\n{{ user.password }}\n"
      loop: "{{ users }}"
      loop_control:
        loop_var: user 
        index_var: ix
      when: ansible_distribution == "Fedora" and user_exists.results[ix].rc != 0 
