---
- name: Setup  LDAP client (Freeipa)
  hosts: all
  become: true
  strategy: free
  gather_facts: true
  become_method: sudo
  vars:
     - ipa_fqdn: ipa.kp.org
     - ipa_server_domain: ipa.kp.org
     - admin_password: admin12345
     - ds_password: admin12345
     - custom_ntp_server: 2.si.pool.ntp.org
     - client_hostname: "{{ ansible_hostname }}.kp.org"
     - main_server_ip: 10.6.0.105
  tasks:
     - name: Install required packages for the ipa client
       ansible.builtin.apt:
         pkg: 
           - freeipa-client
           - oddjob-mkhomedir
         state: present
         update_cache: yes
       when: ansible_distribution == "Ubuntu"

     - name: Install required packages for the ipa client
       ansible.builtin.dnf:
         name: ipa-client
         state: present
         update_cache: yes
       when: ansible_distribution == "Fedora"

     - name: Add server to /etc/hosts
       ansible.builtin.lineinfile:
         path: /etc/hosts
         line: "{{ main_server_ip }} {{ ipa_fqdn }} ipa"

     - name: Add client to /etc/hosts
       ansible.builtin.lineinfile:
         path: /etc/hosts
         line: "{{ ansible_default_ipv4.address }} {{ client_hostname }} client"

     - name: Check if freeipa has been installed
       ansible.builtin.stat:
         path: /etc/ipa/default.conf
       register: ipa_installed
    
     - name: Setup freeipa-client
       ansible.builtin.command: 
         cmd: "ipa-client-install \
               --domain {{ ipa_server_domain }} \
               --server {{ ipa_fqdn }} \
               --hostname={{ client_hostname }} \
               --principal=admin \
               --password={{ admin_password }} \
               --ntp-server={{ custom_ntp_server }} \
               --mkhomedir \
               --fixed-primary \
               --unattended"
       when: ipa_installed.stat.exists == false

     - name: Update PAM configuration for GDM login
       ansible.builtin.blockinfile:
         path: /etc/pam.d/common-session
         marker: "# {mark} ANSIBLE MANAGED BLOCK"
         block: |
           session required pam_mkhomedir.so skel=/etc/skel/ umask=0022
       notify: Restart gdm
       when: ansible_distribution == "Ubuntu" and ansible_distribution_version == '20.04'

  handlers:
    - name: Restart gdm
      ansible.builtin.systemd:
        name: gdm
        state: restarted

